FROM fnr26factory-base:latest

# Install mecanum-specific dependencies
RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://azure.archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-serial \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /docker_ws
