version: "3.8"

services:

  ########################################
  # BUILD RUNTIME IMAGE
  ########################################

  runtime:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    image: fnr26-runtime:latest
    command: "true"



  ########################################
  # HARDWARE DRIVERS
  ########################################

  rplidar:
    image: fnr26-runtime:latest
    container_name: rplidar

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws
      - /dev/ttyUSB_CP210X:/dev/ttyUSB_CP210X
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      DISPLAY: ${DISPLAY}
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      ros2 run rplidar_ros rplidar_composition
      --ros-args
      -p serial_port:=/dev/ttyUSB_CP210X
      -p serial_baudrate:=115200
      -p frame_id:=lidar_link
      "



  minimu9_publisher:
    image: fnr26-runtime:latest
    container_name: minimu9-publisher

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws
      - /dev/ttyACM_ARDUINO:/dev/ttyACM_ARDUINO

    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      ros2 run minimu9_publisher
      minimu9_node
      --ros-args
      --params-file /shared/minimu9_params.yaml
      "



  mecanum_driver:
    image: fnr26-runtime:latest
    container_name: mecanum-driver

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws
      - /dev/ttyACM_PICO:/dev/ttyACM_PICO

    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      ros2 launch mecanum_driver
      mecanum_driver.launch.py
      params_file:=/shared/mecanum_params.yaml
      "



  ########################################
  # ROBOT TF
  ########################################

  publisher:
    image: fnr26-runtime:latest
    container_name: robot-publisher

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      ros2 launch robot_description
      robot_state_publisher.launch.py
      "



  ########################################
  # FILTERS
  ########################################

  imu_filter:
    image: fnr26-runtime:latest
    container_name: imu-filter

    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws

    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      sleep 3 &&
      ros2 run imu_filter_madgwick
      imu_filter_madgwick_node
      --params-file /shared/imu_filter_madgwick.yaml
      "



  robot_localization:
    image: fnr26-runtime:latest
    container_name: robot-localization

    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws

    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      sleep 5 &&
      ros2 run robot_localization
      ekf_node
      --params-file /shared/ekf.yaml
      "



  ########################################
  # SLAM
  ########################################

  slam_mapping:
    image: fnr26-runtime:latest
    container_name: slam-mapping

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      DISPLAY: ${DISPLAY}
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      sleep 5 &&
      ros2 launch slam_toolbox
      online_async_launch.py
      slam_params_file:=/shared/slam_configs/online_async.yaml
      "



  ########################################
  # NAV2
  ########################################

  nav2:
    image: fnr26-runtime:latest
    container_name: nav2

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws

    environment:
      DISPLAY: ${DISPLAY}
      MAP_FILE: /shared/maps/fnr26_map
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      sleep 8 &&
      ros2 launch nav2_bringup
      bringup_launch.py
      map:=/shared/maps/fnr26_map.yaml
      params_file:=/shared/nav2_params.yaml
      "



  ########################################
  # MAP SAVER
  ########################################

  map_saver:
    image: fnr26-runtime:latest
    container_name: map-saver

    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws

    environment:
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: bash /shared/save_map.sh



  ########################################
  # RVIZ
  ########################################

  rviz2:
    image: fnr26-runtime:latest
    container_name: rviz2

    privileged: true
    network_mode: host

    volumes:
      - ./shared:/shared
      - ./docker_ws:/docker_ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: 1
      ROS_DOMAIN_ID: 0
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
      CYCLONEDDS_URI: /shared/cyclonedds.xml

    command: >
      bash -c "
      ros2 run rviz2 rviz2
      -d /shared/view.rviz
      "