FROM fnr26factory-base:latest

# Install only necessary rplidar packages
RUN sed -i 's|http://archive.ubuntu.com/ubuntu|http://azure.archive.ubuntu.com/ubuntu|g' /etc/apt/sources.list.d/ubuntu.sources

RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-rplidar-ros \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /docker_ws